@echo off
echo Starting PhD Opportunity Finder Application...

echo Starting Backend (Flask)...
start cmd /k "cd backend && python app.py"

echo Starting Frontend (React)...
start cmd /k "cd frontend && npm start"

echo Both servers are starting. Please wait a moment...
echo Backend will be available at http://localhost:5000
echo Frontend will be available at http://localhost:3000
